version: "3.9"

services:
  auto-gpt:
    depends_on:
      - redis
    build: ./
    env_file:
      - .env
    volumes:
      - "./autogpt:/app"  # Volume para o código do app
      - ".env:/app/.env"  # Volume para o arquivo .env
      - "/mnt/g:/mnt/google-drive"  # Diretório onde o Google Drive será montado no contêiner
     # - "/caminho/local/rclone.conf:/root/.config/rclone/rclone.conf"  # Monte o rclone.conf (credenciais do Google Drive)
    #profiles: ["exclude-from-up"]
   # entrypoint: ["/bin/bash", "-c", "rclone mount gdrive:/ /mnt/gdrive --config /root/.config/rclone/rclone.conf --vfs-cache-mode writes & exec auto-gpt"]

  redis:
    image: "redis/redis-stack-server:latest"
